package.json, server.js
1. Checkout `connect-to-mongodb`
2. Run `yarn install`
3. Add line to your env: `export MLAB_PASSWORD=kennel`
4. Run the server
5. Ensure that there are no errors
Ignore this warning:
```
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
```
Bookmark the [mLab control panel](https://www.mlab.com/databases/heroku_vhdmcrh0)
=> Connect to mongodb

cerberus-app.postman_collection
=> Use specific id for postman requests and add tests

client/app/app.module.ts, client/app/check-in/check-in.component.spec.ts, client/app/check-in/check-in.component.ts, client/app/shared/visit.ts, client/app/shared/volunteer.service.spec.ts, client/app/shared/volunteer.service.ts, client/app/shared/volunteer.ts, client/app/sign-up/sign-up.component.spec.ts, client/app/visit-history/visit-history.component.html, client/app/visit-history/visit-history.component.spec.ts, client/app/visit-history/visit-history.component.ts, package.json
=> Visit history component

client/app/volunteer-check-in/check-in-form/check-in-form.component.spec.ts, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.css, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.html, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.spec.ts, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.ts, client/app/volunteer-check-in/volunteer-check-in.component.html, client/app/volunteer-check-in/volunteer-check-in.component.spec.ts, client/app/volunteer-check-in/volunteer-check-in.component.ts
- Shorter than 2 characters
- Longer than 30 characters
- Using numbers or symbols other than '-'
=> New volunteer form validation

client/app/shared/volunteer.service.ts, package.json, server/models/volunteer.ts
This PR encompasses Issue #52 and ensures volunteer validation on the server side.
**Test**
Note: Use postman to test since there is client side validation in place.
=> Server side sign up validation

client/app/app.component.spec.ts, client/app/app.component.ts, client/app/app.module.ts, client/app/home/home.component.spec.ts, client/app/home/home.component.ts, client/app/reducers/visit.spec.ts, client/app/reducers/visit.ts, client/app/services/base.service.ts, client/app/services/visit.service.spec.ts, client/app/services/visit.service.ts, client/app/tsconfig.json, client/app/visit-history/visit-history.component.spec.ts, client/app/visit-history/visit-history.component.ts, client/app/volunteer-check-in/check-in-form/check-in-form.component.spec.ts, client/app/volunteer-check-in/check-in-form/check-in-form.component.ts, package.json, server/handlers/base.spec.ts, server/handlers/base.ts
This includes changes to the base handler for server. I'll push postman updates in a separate PR to keep this one slim.
=> Ngrx for visit

client/app/app.module.ts, client/app/models/volunteer.ts, client/app/reducers/visit.spec.ts, client/app/reducers/volunteer.spec.ts, client/app/reducers/volunteer.ts, client/app/services/volunteer.service.spec.ts, client/app/services/volunteer.service.ts, client/app/visit-history/visit-history.component.ts, client/app/volunteer-check-in/check-in-form/check-in-form.component.spec.ts, client/app/volunteer-check-in/check-in-form/check-in-form.component.ts, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.spec.ts, client/app/volunteer-check-in/new-volunteer-form/new-volunteer-form.component.ts
This PR encompasses Issue #69. 
**Test**
1. Sign up a new volunteer
=> Volunteer ngrx

client/app/login/login.component.html, client/app/login/login.component.spec.ts, client/app/login/login.component.ts
There is not an Issue associated with this PR. 
**Test**
=> Login enhancements

client/app/models/user.ts, client/app/services/user.service.spec.ts, client/app/services/user.service.ts, server/models/user.ts
This PR encompasses Issue #95.
**Before Testing**
**Test**
=> Email sensitivity

client/app/components/volunteer-check-in/check-in-form/signature-field/signature-field.component.ts, package.json, server/models/visit.ts
This PR encompasses #102. 
**Test**
=> Sig key error

client/app/components/volunteer-check-in/check-in-form/check-in-form.component.ts
Fix navigation to `/home` after checking out.
=> Fix navigate after checking out

client/app/app.module.ts, client/app/components/visit-data-display/daily-hours-chart/daily-hours-chart.component.html, client/app/components/volunteer-check-in/check-in-form/check-in-form.component.css, client/app/components/volunteer-check-in/check-in-form/check-in-form.component.html, client/app/components/volunteer-check-in/check-in-form/check-in-form.component.spec.ts, client/app/components/volunteer-check-in/check-in-form/check-in-form.component.ts, client/app/components/volunteer-check-in/volunteer-check-in.component.css, client/app/components/volunteer-check-in/volunteer-check-in.component.html, client/app/components/volunteer-check-in/volunteer-check-in.component.spec.ts, client/app/components/volunteer-check-in/volunteer-check-in.component.ts
`check-in-form` changes:
- Replace pet name text field with radio buttons.
- Refactor filter/find logic as pure functions.
- Improve flex layout usage.
- Redesign buttons.
=> Redesign and refactor check-in-form

client/app/components/volunteer-check-in/check-in-form/check-in-form.component.css, client/app/components/volunteer-check-in/check-in-form/check-in-form.component.html, client/app/components/volunteer-check-in/volunteer-check-in.component.html
Fix `volunteer-check-in` flex layouts in iOS.
=> Fix volunteer-check-in flex layouts for iOS

client/app/app.module.ts, client/app/components/getting-started/getting-started.component.spec.ts, client/app/components/getting-started/getting-started.component.ts, client/app/components/location-check-in/check-in-form/check-in-form.component.spec.ts, client/app/components/location-check-in/check-in-form/check-in-form.component.ts, client/app/components/location-check-in/new-volunteer-form/new-volunteer-form.component.spec.ts, client/app/components/location-check-in/new-volunteer-form/new-volunteer-form.component.ts, client/app/components/login/login.component.spec.ts, client/app/components/login/login.component.ts, client/app/services/error.service.spec.ts, client/app/services/error.service.ts, client/app/services/snack-bar.service.spec.ts, client/app/services/snack-bar.service.ts
Abstract out all snack bar logic to `SnackBarService`
=> Snackbar service

src/app/components/check-in/check-in-form/check-in-form.component.ts, src/app/components/check-in/new-volunteer-form/new-volunteer-form.component.html, src/app/components/check-in/new-volunteer-form/new-volunteer-form.component.ts
Use `FormGroupDirective.resetForm()` to reset form without validation errors on submit.
=> Fix validation errors on submit

.gitignore, package.json, src/app/actions/router.actions.ts, src/app/app.module.ts, src/app/components/check-in/check-in-form/check-in-form.component.ts, src/app/components/check-in/check-in.component.ts, src/app/components/check-in/new-volunteer-form/new-volunteer-form.component.ts, src/app/components/data-display/daily-hours-chart/daily-hours-chart.component.ts, src/app/components/data-display/data-display.component.ts, src/app/components/data-display/visit-history-table/visit-history-table.component.ts, src/app/components/getting-started/getting-started.component.ts, src/app/components/getting-started/new-organization-form/new-organization-form.component.ts, src/app/components/getting-started/new-user-form/new-user-form.component.ts, src/app/components/layout/header/header.component.html, src/app/components/layout/header/header.component.scss, src/app/components/layout/header/header.component.ts, src/app/components/layout/layout.component.scss, src/app/components/login/login.component.ts, src/app/components/organization-dashboard/volunteer-menu/volunteer-menu.component.ts, src/app/effects/check-in.effects.ts, src/app/effects/login.effects.ts, src/app/effects/router.effects.ts, src/app/reducers/index.ts, yarn.lock
* Add [@ngrx/router-store](https://github.com/ngrx/platform/blob/master/docs/store/README.md) dependency.
* Add custom navigation actions and effects.
* Update navigation logic to use dispatches.
=> Add @ngrx/router-store

src/app/actions/check-in.actions.ts, src/app/components/check-in-form/check-in-form.component.html, src/app/components/check-in-form/check-in-form.component.spec.ts, src/app/components/check-in-form/check-in-form.component.ts, src/app/components/new-organization-form/new-organization-form.component.ts, src/app/components/new-user-form/new-user-form.component.ts, src/app/components/new-volunteer-form/new-volunteer-form.component.ts, src/app/containers/check-in/check-in.component.html, src/app/containers/check-in/check-in.component.ts, src/app/containers/getting-started/getting-started.component.html, src/app/effects/check-in.effects.ts, src/app/services/volunteer.service.ts
* Dispatch correct action on check out.
* Center signature field.
* Rename event emitters and handlers.
=> Fix Check-In Form Issues

src/app/services/auth.service.spec.ts, src/app/services/auth.service.ts, src/app/services/base.service.ts, src/app/services/error.service.spec.ts, src/app/services/error.service.ts
Resolves #183.
Update ErrorService to handle Firebase errors.
=> Firebase error handling

src/app/actions/app.actions.ts, src/app/actions/settings.actions.ts, src/app/app.module.ts, src/app/components/new-user-form/new-user-form.component.html, src/app/components/new-user-form/new-user-form.component.scss, src/app/components/new-user-form/new-user-form.component.ts, src/app/components/user-form/user-form.component.html, src/app/components/user-form/user-form.component.scss, src/app/components/user-form/user-form.component.spec.ts, src/app/components/user-form/user-form.component.ts, src/app/containers/getting-started/getting-started.component.html, src/app/containers/getting-started/getting-started.component.spec.ts, src/app/containers/getting-started/getting-started.component.ts, src/app/containers/settings-page/settings-page.component.html, src/app/containers/settings-page/settings-page.component.scss, src/app/containers/settings-page/settings-page.component.spec.ts, src/app/containers/settings-page/settings-page.component.ts, src/app/effects/login.effects.spec.ts, src/app/effects/settings.effects.spec.ts, src/app/effects/settings.effects.ts, src/app/services/auth.service.ts, src/app/services/snack-bar.service.ts
Allow the user to update their user details.
1. Get user id from firebase database. 
2. Go to the settings page and update all information.
=> User settings form

src/app/app.component.html, src/app/app.component.spec.ts, src/app/components/header/header.component.html, src/app/components/header/header.component.ts, src/app/containers/check-in/check-in.component.ts, src/app/containers/getting-started/getting-started.component.ts, src/app/containers/login/login.component.ts, src/app/containers/organization-dashboard/organization-dashboard.component.ts, src/app/containers/settings-page/settings-page.component.ts, src/app/models/header-options.ts
Resolves #203 
Hide settings button when on settings page.
=> Hide settings icon

package.json, src/app/actions/settings.actions.ts, src/app/components/reports-form/reports-form.component.spec.ts, src/app/components/reports-form/reports-form.component.ts, src/app/containers/settings-page/settings-page.component.html, src/app/containers/settings-page/settings-page.component.ts, src/app/effects/settings.effects.spec.ts, src/app/effects/settings.effects.ts, src/app/models/report.ts, src/app/models/visit.ts, src/app/reducers/settings.reducer.spec.ts, src/app/reducers/settings.reducer.ts, src/app/services/base.service.ts, src/app/services/visit.service.ts, yarn.lock
A pdf is generated based on the information entered in the form.
=> Add pdf generator

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Set guidelines for repository contributors.
- Add pull request and issue templates.
=> GitHub templates

.travis.yml, README.md, karma.conf.js, package.json, yarn.lock
- Add Codecov steps to Travis.
- Add Codecov badge to README.
=> Codecov integration

src/app/app-routing.module.ts, src/app/containers/settings-page/settings-page.component.html, src/app/containers/settings-page/settings-page.component.ts, src/app/functions/helpers.functions.ts
- Members can only login and edit User settings.
- Members and admin cannot access Permission tab.
=> Authenticate or deny roles

src/app/actions/login.actions.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/components/email-dialog/email-dialog.component.html, src/app/components/email-dialog/email-dialog.component.spec.ts, src/app/components/email-dialog/email-dialog.component.ts, src/app/components/index.ts, src/app/components/password-dialog/password-dialog.component.html, src/app/components/password-dialog/password-dialog.component.spec.ts, src/app/components/password-dialog/password-dialog.component.ts, src/app/containers/index.ts, src/app/containers/login/login.component.html, src/app/containers/login/login.component.scss, src/app/containers/login/login.component.spec.ts, src/app/containers/login/login.component.ts, src/app/effects/login.effects.spec.ts, src/app/effects/login.effects.ts, src/app/services/auth.service.spec.ts, src/app/services/auth.service.ts, src/app/services/error.service.spec.ts, src/app/services/error.service.ts, src/app/services/snack-bar.service.ts
- Provides ability to reset password.
- When providing invalid credentials to login, custom error message is displayed for security.
=> Forgot pwd attempt 2

src/app/containers/join-page/join-page.component.html, src/app/containers/join-page/join-page.component.spec.ts, src/app/containers/join-page/join-page.component.ts
- Add TOS to join organization feature.
=> Add tos to join org

karma.conf.js, package.json
- Add `-cc` flag to `test:ci` script.
=> Fix Codecov - add code coverage flag to test:ci script

src/app/app.component.ts, src/app/components/check-in-form/check-in-form.component.html, src/app/components/daily-hours-chart/daily-hours-chart.component.html, src/app/components/daily-hours-chart/daily-hours-chart.component.scss, src/app/components/data-table/data-table.component.html, src/app/components/data-table/data-table.component.ts, src/app/components/header/header.component.html, src/app/components/volunteer-menu/volunteer-menu.component.html, src/app/containers/check-in/check-in.component.html, src/app/containers/check-in/check-in.component.scss, src/app/containers/check-in/check-in.component.ts, src/app/containers/organization-dashboard/organization-dashboard.component.ts
- Fix visit history table clearing on navigation.
- Update bottom margins for data display components.
- Change capitalization of button labels.
=> Data display enhancements

src/app/components/check-in-form/check-in-form.component.spec.ts, src/app/components/check-in-form/check-in-form.component.ts, src/app/components/daily-hours-chart/daily-hours-chart.component.ts, src/app/effects/settings.effects.ts, src/app/functions/capitalize.functions.spec.ts, src/app/functions/capitalize.functions.ts, src/app/functions/date-format.functions.spec.ts, src/app/functions/helpers.functions.spec.ts, src/app/functions/helpers.functions.ts, src/app/models/visit.ts, src/app/models/volunteer.ts, src/app/reducers/model.reducer.spec.ts, src/app/reducers/model.reducer.ts, src/app/services/base.service.spec.ts, src/app/services/base.service.ts, src/app/services/organization.service.ts, src/app/services/site.service.ts, src/app/services/user.service.ts, src/app/services/visit.service.spec.ts, src/app/services/visit.service.ts, src/app/services/volunteer.service.ts
- Move pure functions to files in `functions` directory.
- Improve test coverage and add specs for Firestore functions.
=> Refactor functions and improve test coverage

src/app/components/data-display/data-display.component.html, src/app/components/data-display/data-display.component.spec.ts, src/app/components/data-display/data-display.component.ts, src/app/components/data-table/data-table.component.html, src/app/components/data-table/data-table.component.spec.ts, src/app/components/data-table/data-table.component.ts, src/app/containers/settings-page/settings-page.component.spec.ts
- Add `getRowColor` binding to data table.
- Set background color for active visit rows to pale green.
=> Highlight active visits

src/app/actions/app.actions.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/components/data-display/data-display.component.spec.ts, src/app/components/data-display/data-display.component.ts, src/app/components/index.ts, src/app/components/loader/loader.component.html, src/app/components/loader/loader.component.scss, src/app/components/loader/loader.component.spec.ts, src/app/components/loader/loader.component.ts, src/app/components/sidenav/sidenav.component.ts, src/app/functions/helpers.functions.ts, src/app/reducers/app.reducer.ts, src/app/reducers/auth.reducer.ts, src/app/services/base.service.spec.ts, src/app/services/user.service.ts
- Keep header component displayed during load.
- Add loader component.
- Display loader during model load and hide after sidenav and chart animations complete. Resolves #266
=> Polish app render

src/app/containers/find-organization/find-organization.component.html, src/app/containers/find-organization/find-organization.component.scss, src/app/containers/find-organization/find-organization.component.spec.ts, src/app/containers/find-organization/find-organization.component.ts, src/app/containers/home/home.component.html, src/app/containers/home/home.component.scss, src/app/containers/home/home.component.spec.ts, src/app/containers/home/home.component.ts, src/app/containers/join-page/join-page.component.html, src/app/containers/join-page/join-page.component.spec.ts, src/app/containers/login/login.component.html, src/app/containers/login/login.component.scss, src/styles.scss
1. Remove padding from login page. 
2. Center login/live data text on home page.
3. Center input icon button for live data on home page.
4. Make Join Organization/New Organization buttons on home page more subtle.
=> Home page enhancements

package.json, src/app/functions/helpers.functions.spec.ts, src/app/functions/helpers.functions.ts, src/app/mock/objects/volunteer.mock.ts, src/app/root/containers/header/header.component.html, src/app/root/containers/header/header.component.scss, src/app/root/containers/header/header.component.spec.ts, src/app/root/containers/header/header.component.ts, src/app/root/containers/root/root.component.html, src/app/root/containers/root/root.component.spec.ts, src/app/root/store/selectors/layout.selectors.ts, src/app/sign-up/containers/getting-started/getting-started.component.ts, src/app/volunteer-system/components/check-in-form/check-in-form.component.html, src/app/volunteer-system/components/check-in-form/check-in-form.component.scss, src/app/volunteer-system/components/check-in-form/check-in-form.component.spec.ts, src/app/volunteer-system/components/check-in-form/check-in-form.component.ts, src/app/volunteer-system/components/new-volunteer-form/new-volunteer-form.component.html, src/app/volunteer-system/components/new-volunteer-form/new-volunteer-form.component.scss, src/app/volunteer-system/components/signature-field/signature-field.component.html, src/app/volunteer-system/components/signature-field/signature-field.component.scss, src/app/volunteer-system/components/signature-field/signature-field.component.spec.ts, src/app/volunteer-system/components/signature-field/signature-field.component.ts, src/app/volunteer-system/containers/check-in/check-in.component.html, src/app/volunteer-system/containers/check-in/check-in.component.scss, src/styles.scss
- Select volunteer on clicking a volunteer option, rather than just matching the name.
- Add more directions to improve guidance during check-in process.
- Improve styles.
- Simplify component logic.
- Fix missing headers.
- Add `--aot` and `--no-progress` flags to CI build scripts.
=> Check-in enhancements

src/app/auth/store/effects/session.effects.spec.ts, src/app/auth/store/effects/session.effects.ts, src/app/volunteer-system/containers/check-in/check-in.component.html, src/app/volunteer-system/containers/check-in/check-in.component.scss
- Add missing logic to load member data.
- Add "Handcrafted with ❤️ in NOLA." banner to check-in page.
=> Fix member data load

src/app/shared/components/data-table/data-table.component.html, src/app/shared/components/data-table/data-table.component.scss, src/app/shared/components/data-table/data-table.component.spec.ts, src/app/shared/components/data-table/data-table.component.ts
Dynamically set css for the data table given the isEditable property.
=> Dynamically select data table css given isEditable

src/app/shared/components/services-agreement/services-agreement.component.html
Make TOS and Privacy responsive.
=> Make tos and privacy responsive

src/app/auth/effects/session.effects.ts, src/app/public/public.module.ts, src/app/shared/components/user-form/user-form.component.spec.ts, src/app/shared/components/user-form/user-form.component.ts
Allow user to update user information.
=> Pass in member role and id when updating member

src/app/auth/effects/auth.effects.ts, src/app/auth/selectors/auth.selectors.ts, src/app/core/selectors/members.selectors.ts, src/app/settings/selectors/user-settings.selectors.ts, src/app/teams/effects/teams-page.effects.ts
* Fixes errors from accessing undefined `userInfo` on logout.
=> Handle undefined user info values in auth state

src/app/teams/components/selected-team-toolbar/selected-team-toolbar.component.ts
Allow user to deselect site on teams module.
=> Allow user to deselect site
